### PR TITLE
import lasgun_1.1.pk3 by chris807 (2016-07-11), port to master

### PR DESCRIPTION
**Pull request by illwieckz**
In first person view it works as expected:

[lasgun](https://dl.illwieckz.net/b/unvanquished/wip/lasgun/unvanquished_2020-05-12_112151_000.jpg)

[lasgun](https://dl.illwieckz.net/b/unvanquished/wip/lasgun/unvanquished_2020-05-12_114426_000.jpg)

[lasgun](https://dl.illwieckz.net/b/unvanquished/wip/lasgun/unvanquished_2020-05-12_231550_000.jpg)

But in third person view the first person arms are displayed, and the third person arms are not correctly positioned:

[lasgun](https://dl.illwieckz.net/b/unvanquished/wip/lasgun/unvanquished_2020-05-12_233051_000.jpg)

Also I noticed the game says:

```
Warn: Cannot find bone index root, using root bone
```

While `models/weapons/lgun/weapons.cfg` sets:

```
rotationBone      root
```

So it looks like the game is doing what is expected by using the root bone when there is no bone named `root`, we can probably edit the game to do it explicitly.

If we find a way to fix the third person view, this would be shipable in 0.52 release.

### CODE REVIEW

**Comment by illwieckz** [comment]
Also, we can see the specular map embed in alpha channel another map we don't use, it would be good to know what it is.

RGB (specular map):

[lasgun](https://dl.illwieckz.net/b/unvanquished/wip/lasgun/lgun_s.rgb.png)

Alpha (unknown map):

[lasgun](https://dl.illwieckz.net/b/unvanquished/wip/lasgun/lgun_s.a.png)

**Comment by illwieckz** [comment]
The reactor also has such texture in specular alpha channel, and for both models chris said the model have: `Diffuse,Normal,Specular-Gloss,Glow` textures.

**Comment by illwieckz** [comment]
I've restored the legacy third person view model. This PR is mergeable.

**Comment by hypov8** [comment]
did you need the gun like this?

unvanquished_2020-11-12_004409_000

**Comment by illwieckz** [comment]
I would prefer something like this (nothing to compensate, eh):
[](https://dl.illwieckz.net/b/unvanquished/wip/lasgun/unvanquished_2020-11-11_135134_000.jpg)

Joke aside, what happens if you type this in console:

```
/toggle cg_thirdPerson ; delay 1 toggle cg_thirdPerson
```

Is the model still at the same expected place, with correct orientation, etc?

What is the format you use for the third person model, iqm? md3?

**Comment by illwieckz** [comment]
This is that I managed to remove the hand mesh but as soon as I remove the hand skeletons, everything goes wrong. Also, if I keep the unused skeleton, it displays somewhat correctly, I can rescale, move the `wrapon_tag` to somewhat place the weapon in hand, but as soon as I toggle third person with enough frame (1) to display the first person between, the weapon get reset to some coordinate and scale (even if I upscaled the model when compiling to iqm).

Thing is that I only tried iqm as third person model. I noticed all other weapons use md3 for third person models… Maybe we have bugs for non-md3 third person models that went unnoticed because we don't do it yet… I don't know how to convert iqm to md3 though.

**Comment by hypov8** [comment]
its am md3 model. 
i just replaced the existing file models\weapons\lgun\vwep.md3

**Comment by illwieckz** [comment]
How did you do the md3 model?

**Comment by illwieckz** [comment]
I mean, converted from iqm to md3… That's the step I'm missing.

**Comment by hypov8** [comment]
im using max.. is suports md3 export.
i converted the iqm in noesis to fbx

**Comment by illwieckz** [comment]
Ah, because your model does not look that bad but miss some geometry…

**Comment by hypov8** [comment]
world player models should be at a ruduced poly compared to 1st person. so im optimizing it :)
the 2 white parts can be put back later or skin updated with the colors to keep poly lower

**Comment by illwieckz** [comment]
yeah but at this point those details would never be seen, since they are out of view from first person perspective… also it would be cool to keep glow map and material maps… =)

**Comment by illwieckz** [comment]
With [IqeBrowser](https://www.moddb.com/mods/r-reinhard/addons/iqebrowser) there is an option to export an `.obj` file and I was hoping to convert it to `md3` using [Maverick Model 3D](https://clover.moe/mm3d/) but it does not read the produced obj file…

**Comment by hypov8** [comment]
you can try noesis. it will even export an md3
i have not worked out the shader name.  thats why it dont have all the first person maps (glow etc..)

**Comment by illwieckz** [comment]
With this plugin I can export to md3 from Blender after having imported from obj generated with IqeBrowser:
https://github.com/axredneck/blender-md3-2.8/tree/blender2.8

But then texturing is lost (even if it works in Blender) but I can reapply it with Maverick Model 3D and save as md3 again (I can then replace texture name with ghex given I can search for an existing one I know).

But, the tags seem to be lost of course, meh…

**Comment by illwieckz** [comment]
The shader name is `models/weapons/lgun/lgun`.

**Comment by illwieckz** [comment]
Anyway, your model looks really ok for the size and placement. If you can restore the white and the black relief on the front, and given the material would be complete, that would be enough.

**Comment by hypov8** [comment]
how is that

file [vwep.zip](https://github.com/UnvanquishedAssets/res-weapons_src.dpkdir/files/5525511/vwep.zip)

unvanquished_2020-11-12_035228_000

**Comment by illwieckz** [comment]
Man, you're a true wizard, you saved the day (and more than that!!!), that is a-we-so-me.

**Comment by hypov8** [comment]
im glad you like it :) 
all that kpq3 experence..
it probable needs some vertex welding to match the existing bumpmap. 
but should get you going for now

**Comment by hypov8** [comment]
welded some vertex, stretch front of gun, shrunk stock to prevent it clipping player, shifted tag_flash..
anything else?

unvanquished_2020-11-12_045637_000

**Comment by illwieckz** [comment]
That's really good, really, if you have a new file with those micro optimization then send it please. But really, that's seems to be good enough! :heart_eyes:

[lasgun](https://dl.illwieckz.net/b/unvanquished/wip/lasgun/unvanquished_2020-11-11_184212_000.jpg)

[lasgun](https://dl.illwieckz.net/b/unvanquished/wip/lasgun/unvanquished_2020-11-11_184537_000.jpg)

[lasgun](https://dl.illwieckz.net/b/unvanquished/wip/lasgun/unvanquished_2020-11-11_184620_000.jpg)

[lasgun](https://dl.illwieckz.net/b/unvanquished/wip/lasgun/unvanquished_2020-11-11_184719_000.jpg)

Yeah, I made a special glow map for the third person view (you'll notice the (non-animated) display!), details everywhere!

[details, details everywhere](https://i.imgflip.com/4lzo2w.jpg)

**Comment by illwieckz** [comment]
OK, so the new lasgun implementation is complete. Thanks to true skills of great wizard @hypov8!
If I understood correctly he said he did some minor updates so I'm waiting for them to merge the PR, but otherwise, this is fully functional and looks **awesome in space**.

**Comment by hypov8** [comment]
how do you get the other player model?

this is update version 2
[vwep_002.zip](https://github.com/UnvanquishedAssets/res-weapons_src.dpkdir/files/5527552/vwep_002.zip)

**Comment by illwieckz** [comment]
when loading a map with `/devmap`, just fills your accounts this way:

```
/give momentum 999
```

to unlock your team stage,

```
/give funds 999
```

to give you money / evo points,

you may also do `/give bp 999` to give you build points, just to be exhaustive.

Then at the armoury in the buy menu you'll notice a tab for non-weapons things, like light armour, medium armour, battlesuit, radar, jetpack… :wink:

**Comment by hypov8** [comment]
added display as a new mesh and using correct shader
increased size slightly to match battlesuit
version 3 [vwep_003.zip](https://github.com/UnvanquishedAssets/res-weapons_src.dpkdir/files/5527826/vwep_003.zip)

"give all" should give all those items, but they are not included.
also i dont know how to view model outside of packs, even with devmap and sv_pure 0

there is an issue with battlesuit and the "pain saw" when you shoot.(missing bones/animation?) 
also player shadows dont seem to work. lighttransform seems incorrect.
i am using the 0.51 release  version

unvanquished_2020-11-12_130848_000
unvanquished_2020-11-12_131137_000

**Comment by slipher** [comment]
> also i dont know how to view model outside of packs, even with devmap and sv_pure 0

Workflow for quick and dirty modifications to an existing package:

Extract `res-weapons_0.51.dpk` into a folder named `res-weapons_wip.dpkdir`, which should sit next to the original package. (`wip` is a version string which is arbitrary, but must be "greater" than `0.51`). Then you can make your modifications in this directory tree. Use a which command e.g. `/which scripts/blaster.shader` to check that your dpkdir is being loaded.

**Comment by illwieckz** [comment]
Yay! Our next release will be awesome in space! :tada:

**Pull request merged**
