### PR TITLE
Simply ground fire shader to improve performance

### PR DESCRIPTION
**Pull request by slipher**
See https://github.com/Unvanquished/Unvanquished/issues/1109. I found a way to cut it down to 1 stage which doesn't seem too much worse.

Before: https://imgur.com/a/0oBU5YD

After: https://imgur.com/a/p7TfDQr

### CODE REVIEW

**Comment by illwieckz** [comment]
For sure the animation lools really less smooth, it looks like fire animations from the era of Doom (the first one).
But anyway, this is a placeholder and we need to keep framerate… Maybe it's _bad enough?_

I'll put no veto on this even if it looks like a joke. We need those FPS.

**Comment by illwieckz** [comment]
In fact there is no `rgbGen wave` anymore if I'm right.

**Comment by illwieckz** [comment]
What if:

```c
particles/weapons/flamer/floorfire
{
	// haze
	ejector
	{
		particle
		{
			shader sync gfx/weapons/flamer/haze

			displacement ~15 ~15 5 ~0

			velocityType      static
			velocityDir       linear
			velocityMagnitude 0
			velocity          0 0 1 ~60

			accelerationType      static
			accelerationDir       linear
			accelerationMagnitude 10~10
			acceleration          0 0 1 0

			radius 0 5 45
			alpha  0 .6~.1 0
			rotation ~360 ~360 -
			bounce .01

			lifeTime 1500~50%
		}

		count infinite
		delay 0
		period 500 - ~50%
	}

	// smoke
	ejector
	{
		particle
		{
			shader sync gfx/weapons/flamer/smoke

			displacement ~15 ~15 5 ~0

			velocityType      static
			velocityDir       linear
			velocityMagnitude 0
			velocity          0 0 1 ~60

			accelerationType      static
			accelerationDir       linear
			accelerationMagnitude 10~10
			acceleration          0 0 1 0

			radius 0 10 30~50%
			alpha  0 .6~.1 0
			rotation ~360 ~360 -
			bounce .01

			lifeTime 1500~50%
		}

		count infinite
		delay 0
		period 500 - ~50%
	}

	// flames
	ejector
	{
		particle
		{
			shader sync gfx/weapons/flamer/fire/fire
			displacement ~12 ~12 -1 ~0

			radius 0 4~4 8~6
			alpha  0 .1~.3 0
			rotation 0 0 -
			bounce 0

			dynamicLight 0 50 0 { .25 .25 0 }

			lifeTime 500~60%
		}

		count infinite
		delay 0
		period 50 - ~60%
	}

	// widespread flames
	ejector
	{
		particle
		{
			shader sync gfx/weapons/flamer/fire/fire
			displacement ~27 ~27 -1 ~0

			radius 0 4~4 8~6
			alpha  0 .1~.3 0
			rotation 0 0 -
			bounce 0

			dynamicLight 0 50 0 { .25 .25 0 }

			lifeTime 500~60%
		}

		count infinite
		delay 0
		period 100 - ~60%
	}
}
```

and:

```c
gfx/weapons/flamer/fire/fire
{
	qer_editorImage	gfx/weapons/flamer/fire/fire_p
//	q3map_surfacelight 1000
	surfaceparm nomarks
	surfaceparm nolightmap
	surfaceparm trans
	polygonOffset
	cull none
	sort nearest
	{
		animMap 12 gfx/weapons/flamer/fire/fire1 gfx/weapons/flamer/fire/fire2 gfx/weapons/flamer/fire/fire3 gfx/weapons/flamer/fire/fire4 gfx/weapons/flamer/fire/fire5 gfx/weapons/flamer/fire/fire6 gfx/weapons/flamer/fire/fire7 gfx/weapons/flamer/fire/fire8
		blendFunc GL_ONE GL_ONE
	}
}
```

**Comment by illwieckz** [comment]
This would produce this:

[floor fire](https://dl.illwieckz.net/b/unvanquished/wip/floor-fire/unvanquished_2020-09-19_064205_000.jpg)

[floor fire](https://dl.illwieckz.net/b/unvanquished/wip/floor-fire/unvanquished_2020-09-19_064223_000.jpg)

[floor fire](https://dl.illwieckz.net/b/unvanquished/wip/floor-fire/unvanquished_2020-09-19_064320_000.jpg)

[floor fire](https://dl.illwieckz.net/b/unvanquished/wip/floor-fire/unvanquished_2020-09-19_065204_000.jpg)

[floor fire](https://dl.illwieckz.net/b/unvanquished/wip/floor-fire/unvanquished_2020-09-19_065653_000.jpg)

[floor fire](https://dl.illwieckz.net/b/unvanquished/wip/floor-fire/unvanquished_2020-09-19_070016_000.jpg)

[floor fire](https://dl.illwieckz.net/b/unvanquished/wip/floor-fire/unvanquished_2020-09-19_070931_000.jpg)

[floor fire](https://dl.illwieckz.net/b/unvanquished/wip/floor-fire/unvanquished_2020-09-19_080705_000.jpg)

**Comment by slipher** [comment]
I don't care how it looks as long as it's not slow. You can decide which way to go with since you have many more opinions on this subject.

**Comment by illwieckz** [comment]
OK, anyway, the suggests I made are things added to what you've done, so you may start by merging what you've done.

**Pull request merged**
