### PR TITLE
Final depth fade/heat haze adjustments

### PR DESCRIPTION
**Pull request by slipher**
Final batch of changes to accommodate the engine's depth fade and heat haze fixes.

Though I still hope to make a new particle system for the new painsaw.

### CODE REVIEW

**Comment by illwieckz** [comment]
is the grenade shockwave image still used by another weapon? If yes we may rename it.

**Comment by slipher** [comment]
Yes it's used by lcannon.

**Comment by slipher** [comment]
> is the grenade shockwave image still used by another weapon? If yes we may rename it.

Done.

@DolceTriade Here is a screenshot with the newly re-enabled grenade "flare" image. Note that this only appears for 125 ms.

unvanquished_2024-10-13_220032_000

**Comment by DolceTriade** [comment]
Tested in game too. It seems fine. The blaster spark feels a little small in my tests, overall, it feels like there is little impact

**Review by DolceTriade — APPROVED** [review]

**Comment by slipher** [comment]
> Tested in game too. It seems fine. The blaster spark feels a little small in my tests, overall, it feels like there is little impact

Right, there should be little impact. The commits other than the grenade flare are pretty much making things be the same as in 0.54.

**Pull request merged**
