### PR TITLE
psaw: Replace with new model

### PR DESCRIPTION
**Pull request by DolceTriade**
I made a few alterations to the textures:
 - "Dirtied" texture
 - Changed lights from white to red

Original textures can be found here: https://gitlab.com/Unvanquished/UnvanquishedData/unvanquished-data-dump/-/tree/master/Unused%20Saw.Alex%20Tikkoiev?ref_type=heads

Orig:
unvanquished_2024-10-12_005519_000

Before changes:
unvanquished_2024-04-09_123545_000

After changes:
unvanquished_2024-10-12_004532_000

### CODE REVIEW

**Comment by illwieckz** [comment]
It's preferable to use `.xcf.xz` than `.xcf.zst` as GIMP opens `.xcf.xz` out of the box, also in this case Xz compressed more.

For `.blend` file, Blender supports out of the box a gzipped `.blend` file that just reuses the `.blend` extension. Gzip compresses less than Zstd but that looks good enough for now.

Some comparison:

```
# With Zstd
$ du -shc flash.blend* flash_thirdperson.blend* psaw_d.xcf* saw.blend*
104K	flash.blend.zst
96K	flash_thirdperson.blend.zst
22M	psaw_d.xcf.zst
276K	saw.blend.zst
22M	total

# Without compression
$ du -shc flash.blend* flash_thirdperson.blend* psaw_d.xcf* saw.blend*
1,1M	flash.blend
1,1M	flash_thirdperson.blend
52M	psaw_d.xcf
1,8M	saw.blend
56M	total

# With Xz for .xcf and Gzip for .blend
$ du -shc flash.blend* flash_thirdperson.blend* psaw_d.xcf* saw.blend*
128K	flash.blend
116K	flash_thirdperson.blend
20M	psaw_d.xcf.xz
388K	saw.blend
21M	total
```

**Comment by DolceTriade** [comment]
thx, looks good

**Comment by illwieckz** [comment]
I imported the specular map from the “new saw maps” folder, and I modified it to be affected by the stain too.

unvanquished_2024-10-13_010926_000

unvanquished_2024-10-13_010930_000

https://imgsli.com/MzA2MzUx

**Comment by DolceTriade** [comment]
Nice! Thanks!

**Comment by illwieckz** [comment]
@slipher can you test this package and see what can be done to make the flash works in first person view? Also some flash things may be removed thanks to your recent changes, and you're the one knowing the best about it:

- https://dl.illwieckz.net/b/unvanquished/pkg/preview/res-weapons_0.54.1-20241012-074417-df17692-psaw.dpk

**Comment by DolceTriade** [comment]
https://github.com/DolceTriade/res-thelab_dev.dpkdir/blob/main/models/weapons/psaw/psaw_flash.md3

flash file is missing

**Comment by illwieckz** [comment]
this looks good, and with the iqm human model we get the pose:

unvanquished_2024-10-13_022440_000

bsuit pose is missing but we can live with it for now:

unvanquished_2024-10-13_022456_000

**Pull request merged**
