### PR TITLE
Replace lucifer cannon model with one from weapons unvanquished_0.23.0/main/pakB.pk3 

### PR DESCRIPTION
**Pull request by illwieckz**
Replace the current lucifer canon (in fact a pulse model that got reaffected as a lucifer cannon) with the one we still used at unvanquished  0.24 (but lossless files were found in 0.23.0):

- TGA converted to optimized PNG,
- remplace md5mesh/md5anim files,
- move the material to `scripts/lcannon.shader` like we currently do,
- rename some files,
- remove textures from pulse-as-lcannon model.

### CODE REVIEW

**Comment by illwieckz** [comment]
Here is a test dpk from before I merge this into a res-weapons branch (that's the exact same commits): https://dl.illwieckz.net/b/unvanquished/extra/oldlcannon/res-oldlcannon_0-20220813-085308-9cdef32.dpk

**Comment by DolceTriade** [comment]
When I use the test dpk, I get a lot of warnings. Is that expected? Will that go away if this is merged?

**Comment by illwieckz** [comment]
I don't get any warning when using this branch. What are the warnings you get?

**Comment by DolceTriade** [comment]
Note I'm not using the branch, only the test dpk with fs_extrapaks res-oldlcannon

```
Warn: configs/weapon/level3upg.attr.cfg: unknown token 'ballDmg' 
Warn: configs/weapon/level3upg.attr.cfg: unknown token '110' 
Warn: configs/weapon/level3upg.attr.cfg: unknown token 'ballRadius' 
Warn: configs/weapon/level3upg.attr.cfg: unknown token '75' 
Warn: configs/weapon/blaster.attr.cfg: unknown token 'spread' 
Warn: configs/weapon/blaster.attr.cfg: unknown token '200' 
Warn: configs/weapon/blaster.attr.cfg: unknown token 'damage' 
Warn: configs/weapon/blaster.attr.cfg: unknown token '10' 
Warn: configs/weapon/blaster.attr.cfg: unknown token 'size' 
Warn: configs/weapon/blaster.attr.cfg: unknown token '5' 
Warn: configs/weapon/flamer.attr.cfg: unknown token 'damage' 
Warn: configs/weapon/flamer.attr.cfg: unknown token '14' 
Warn: configs/weapon/flamer.attr.cfg: unknown token 'flightDamage' 
Warn: configs/weapon/flamer.attr.cfg: unknown token '1' 
Warn: configs/weapon/flamer.attr.cfg: unknown token 'splashDamage' 
Warn: configs/weapon/flamer.attr.cfg: unknown token '6' 
Warn: configs/weapon/flamer.attr.cfg: unknown token 'radius' 
Warn: configs/weapon/flamer.attr.cfg: unknown token '25' 
Warn: configs/weapon/prifle.attr.cfg: unknown token 'damage' 
Warn: configs/weapon/prifle.attr.cfg: unknown token '9' 
Warn: configs/weapon/prifle.attr.cfg: unknown token 'size' 
Warn: configs/weapon/prifle.attr.cfg: unknown token '5' 
Warn: configs/weapon/lcannon.attr.cfg: unknown token 'size' 
Warn: configs/weapon/lcannon.attr.cfg: unknown token '5' 
Warn: configs/weapon/abuild.attr.cfg: unknown token 'blobDmg' 
Warn: configs/weapon/abuild.attr.cfg: unknown token '4' 
Warn: configs/weapon/abuild.attr.cfg: unknown token 'blobLockTime' 
Warn: configs/weapon/abuild.attr.cfg: unknown token '2000' 
```

**Comment by illwieckz** [comment]
You may try this instead: https://dl.illwieckz.net/b/unvanquished/extra/oldlcannon/res-weapons_0.53.0-20220914-071555-604c0a2.dpk

It's a build of the current branch.

**Comment by DolceTriade** [comment]
```
Warn: configs/weapon/level3upg.attr.cfg: unknown token 'ballDmg' 
Warn: configs/weapon/level3upg.attr.cfg: unknown token '110' 
Warn: configs/weapon/level3upg.attr.cfg: unknown token 'ballRadius' 
Warn: configs/weapon/level3upg.attr.cfg: unknown token '75' 
Warn: configs/weapon/blaster.attr.cfg: unknown token 'spread' 
Warn: configs/weapon/blaster.attr.cfg: unknown token '200' 
Warn: configs/weapon/blaster.attr.cfg: unknown token 'damage' 
Warn: configs/weapon/blaster.attr.cfg: unknown token '10' 
Warn: configs/weapon/blaster.attr.cfg: unknown token 'size' 
Warn: configs/weapon/blaster.attr.cfg: unknown token '5' 
Warn: configs/weapon/flamer.attr.cfg: unknown token 'damage' 
Warn: configs/weapon/flamer.attr.cfg: unknown token '14' 
Warn: configs/weapon/flamer.attr.cfg: unknown token 'flightDamage' 
Warn: configs/weapon/flamer.attr.cfg: unknown token '1' 
Warn: configs/weapon/flamer.attr.cfg: unknown token 'splashDamage' 
Warn: configs/weapon/flamer.attr.cfg: unknown token '6' 
Warn: configs/weapon/flamer.attr.cfg: unknown token 'radius' 
Warn: configs/weapon/flamer.attr.cfg: unknown token '25' 
Warn: configs/weapon/prifle.attr.cfg: unknown token 'damage' 
Warn: configs/weapon/prifle.attr.cfg: unknown token '9' 
Warn: configs/weapon/prifle.attr.cfg: unknown token 'size' 
Warn: configs/weapon/prifle.attr.cfg: unknown token '5' 
Warn: configs/weapon/lcannon.attr.cfg: unknown token 'size' 
Warn: configs/weapon/lcannon.attr.cfg: unknown token '5' 
Warn: configs/weapon/abuild.attr.cfg: unknown token 'blobDmg' 
Warn: configs/weapon/abuild.attr.cfg: unknown token '4' 
Warn: configs/weapon/abuild.attr.cfg: unknown token 'blobLockTime' 
Warn: configs/weapon/abuild.attr.cfg: unknown token '2000'
```

Still see this. I'll investigate later in the day

**Comment by illwieckz** [comment]
Those files aren't modified by the patch so that's probably caused by something else indeed. They even have been moved back to `unvanquished_src.dpkdir` since https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/commit/3e12b1c409a1e6030ade16ffe650bfdc7593ec69 .

**Comment by DolceTriade** [comment]
Ok, something was just wrong. I tested myself and it all works!

**Comment by DolceTriade** [comment]
Looks great!

**Review by DolceTriade — APPROVED** [review]

**Pull request merged**
