### PR TITLE
Make flamer impact graphics a bit nicer

### PR DESCRIPTION
**Pull request by necessarily-equal**
The flame impact is now only partially opaque, a bit asymetric (longer on one side) and slightly off-centered. Since each impact mark is rotated randomly, this creates a more genuine look for the burnt walls.

### CODE REVIEW

**Comment by necessarily-equal** [comment]
marking as draft because it paints things yellow

image

**Comment by necessarily-equal** [comment]
New version looks like this:

|  | Slight | Strong |
| -- | --- | --- |
| before | image | image |
| after | image | image |

The "yellow painting" was because I thought I added a black background when it was actually blue. I have a strong redshift on my screen so no difference was displayed :laughing:

**Comment by illwieckz** [comment]
If you reexport from an editor, better export a png, to not readd jpg artifacts to jpg artifacts before crn artifacts…

**Comment by necessarily-equal** [comment]
Updated

**Comment by DolceTriade** [comment]
I think it looks better :D

**Comment by illwieckz** [comment]
Wait a moment before merging!

**Comment by illwieckz** [comment]
Optimized files: ~~_removed link_~~
```
Before:

13035	mark.png
36889	mark.xcf

After:

3639	mark.png
15368	mark.xcf.xz
```

Those are just the same ones, smaller.

**Comment by illwieckz** [comment]
You can merge it after you replaced with optimized files. ⬆️

Note: if you push a branch to this repository it makes easier for someone to rewrite the files before merging, like when running file optimizers.

**Comment by illwieckz** [comment]
LOL, the PNG is even smaller than the previous JPG:

```
 gfx/weapons/flamer/mark.jpg    | Bin 4190 -> 0 bytes
 gfx/weapons/flamer/mark.png    | Bin 0 -> 3639 bytes
```

**Review by illwieckz — APPROVED** [review]
LGTM.

**Pull request merged**
